#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=1,vmem=2gb,walltime=00:30:00
#PBS -M rionbr@indiana.edu
#PBS -m abe
#PBS -N ddiindy-coadmin-sda2rda
#PBS -j oe 

cd /N/u/rionbr/Carbonate/DDIIndy/02-computation

printf "\n> Getting MySQL key/pass from config.ini\n"
pass=$(python << EOI
import configparser
c = configparser.ConfigParser()
c.read('../config.ini')
print(c['IU-RDC-MySQL']['pass'])
EOI
)

printf "\n> Processing: CoAdministrations\n"
python 01-compute_coadmin.py

printf "\n> Done.\n"